# Generated by Django 4.0 on 2022-02-22 18:06

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
